In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('MyData.csv')

In [3]:
df.head()

Y  X1  X2  X3
0  43  30  63  33
1  63  45  47  52
2  71  68  67  62
3  61  46  83  42
4  81  66  84  42

In [4]:
X=df.drop('Y',axis=1)

In [5]:
X

X1  X2  X3
0  30  63  33
1  45  47  52
2  68  67  62
3  46  83  42
4  66  84  42
5  36  50  66

In [6]:
X.insert(0,'B0',[1,1,1,1,1,1])

In [7]:
X

B0  X1  X2  X3
0   1  30  63  33
1   1  45  47  52
2   1  68  67  62
3   1  46  83  42
4   1  66  84  42
5   1  36  50  66

In [8]:
Y=df['Y']

In [9]:
X=X.values

In [10]:
X

array([[ 1, 30, 63, 33],
       [ 1, 45, 47, 52],
       [ 1, 68, 67, 62],
       [ 1, 46, 83, 42],
       [ 1, 66, 84, 42],
       [ 1, 36, 50, 66]])

In [11]:
Y=Y.values

In [12]:
Y

array([43, 63, 71, 61, 81, 43])

In [13]:
XT=X.T

In [14]:
XT

array([[ 1,  1,  1,  1,  1,  1],
       [30, 45, 68, 46, 66, 36],
       [63, 47, 67, 83, 84, 50],
       [33, 52, 62, 42, 42, 66]])

In [15]:
XTX=XT.dot(X)

In [16]:
import numpy as np
XTXINV=np.linalg.inv(XTX)

In [17]:
XTXINV

array([[ 1.69580230e+01,  8.31914459e-02, -1.73130574e-01,
        -1.91055228e-01],
       [ 8.31914459e-02,  1.89410821e-03, -1.54994977e-03,
        -1.48031635e-03],
       [-1.73130574e-01, -1.54994977e-03,  2.35593088e-03,
         1.89084867e-03],
       [-1.91055228e-01, -1.48031635e-03,  1.89084867e-03,
         2.80171396e-03]])

In [18]:
XTY=XT.dot(Y)

In [19]:
XTY

array([  362, 18653, 24444, 17899])

In [20]:
BHAT=XTXINV.dot(XTY)

In [21]:
BHAT

array([38.8730967 ,  1.06294938, -0.15180574, -0.40655013])

In [22]:
38.8730967+1.06294938*39+(-0.15180574*59)+(-0.40655013*69)

43.319624889999986